### ISSUE TITLE
Flow init errors despite following instructions using React 0.4. NPM dependencies not correct?

### ISSUE THREAD

**Issue by admmasters** [brentvatne/react-native-modal#10]
![ios simulator screen shot 21 apr 2015 17 58 16](https://cloud.githubusercontent.com/assets/335607/7257803/25a64b7e-e850-11e4-8831-a22c1e474d1d.png)

**Comment by brentvatne** [comment]
@admmasters - did you `npm install`?

**Comment by admmasters** [comment]
Yeah I'm seeing if this is an issue with the version of flow - as other people have reported the same issue.

**Comment by brentvatne** [comment]
@admmasters - ah ok, thanks

**Comment by admmasters** [comment]
Hmmm - still getting the above - but maybe it is related to this issue: https://github.com/facebook/react-native/issues/938 I am on the most recent brew and flow.

**Comment by admmasters** [comment]
Sorry - this seems to happen regardless unfortunately.

**Comment by brentvatne** [comment]
@admmasters - try updating to the latest version `0.2.10` of this lib, I removed the examples from the npm package

**Comment by admmasters** [comment]
Sorry same error - new project - using the "AwesomeProject" tutorial so its a fresh project.

**Comment by brentvatne** [comment]
@admmasters - ok will try this out and fix it for you now, sorry about that

**Comment by brentvatne** [comment]
@admmasters - try out `0.2.11` - seems to be working for me now :smile:

**Comment by admmasters** [comment]
Brilliant - fixed. +1
