### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by chriszorn** [brentvatne/react-native-modal#12]
Went through the steps described. The files are written to the correct location, but I'm getting this message.

flow: Error running command `cd "/Users/chris/myapp/src/react-ios/myapp" && flow --json --timeout 20`:

{"status":500,"message":"Flow found type errors.  If you think these are wrong, make sure your flow bin and .flowconfig are up to date, or disable with --skipflow.","type":"FlowError","errors":[{"description":"E1: \nFailure(\"internal error: package /Users/chris/myapp/src/react-ios/myapp/node_modules/react-native-modal/node_modules/react-native-overlay/package.json not found\")","filename":"/Users/chris/myapp/src/react-ios/myapp/node_modules/react-native-modal/Modal.ios.js","lineNumber":0,"column":0}]}

What's strange is that there is a file at this path: /Users/chris/myapp/src/react-ios/myapp/node_modules/react-native-modal/node_modules/react-native-overlay/package.json

**Comment by brentvatne** [comment]
@chriszorn: fixed?

**Comment by chriszorn** [comment]
Looks like I just needed to restart the react packager

**Comment by brentvatne** [comment]
@chriszorn - oh excellent :smile:
