### ISSUE TITLE
Screenshots in readme is really confusing

### ISSUE THREAD

**Issue by ReadingSteiner** [brentvatne/react-native-modal#13]
just a suggestion :)

**Comment by brentvatne** [comment]
@ReadingSteiner - haha fair, I was a bit lazy on that and just re-used screenshots from other projects :P If you know how to do this could you submit a PR to improve on that? Would be _much_ appreciated!

**Comment by ReadingSteiner** [comment]
@brentvatne  glad to do that :)

**Comment by brentvatne** [comment]
@ReadingSteiner - awesome, merged thanks!
