### ISSUE TITLE
Modal container should have settable pointerEvents

### ISSUE THREAD

**Issue by premasagar** [brentvatne/react-native-modal#16]
Hi. Thanks for this module. For my use case, I am overriding `styles.modal` so that the modal body container is transparent and fills the view: `{position:'absolute', left:0, right:0, top:0, bottom:0}`. I have buttons inside the container. The problem I have is that I need `pointerEvents="box-none"` set on the modal body container, so that touch events pass through, to allow a backdropPress to close the modal.

The [`renderBody()` method](https://github.com/brentvatne/react-native-modal/blob/master/Modal.ios.js#L118) could use `this.props.modalPointerEvents` or maybe better, check for a flag like `this.props.hideModalContainer`.

**Comment by brentvatne** [comment]
Interesting use case! Care to try your hand at a pull request?

**Comment by premasagar** [comment]
OK, sure.

**Comment by premasagar** [comment]
Done: https://github.com/brentvatne/react-native-modal/pull/17
I went with allowing the low-level `pointerEvents` property itself, as there may be use cases for one value or another.
