### ISSUE TITLE
Installation Issue: App goes white after install

### ISSUE THREAD

**Issue by MossP** [brentvatne/react-native-modal#21]
Hi, I tried installing and afterwards my app just went white. I even tried removing the files and rolling back my app's local git and it's still just white.. Something to do with NPM? / versioning?

**Comment by MossP** [comment]
I forget git _ignores_ the "node_modules" folder, manually deleting "react-native-modal" folder from there got my app working again. Any ideas why this happened for me?

**Comment by MossP** [comment]
Some more info that may be of use (I'm new to NPM and react so forgive me if this is of no use):

**ReactNative: v0.4.2**

**Other installed packages:**
_react-native-icons v0.0.5_
_react-native-navbar v0.5.0_
_react-native-router v0.1.3_
_react-native-segmented-view v1.0.1_

**Comment by MossP** [comment]
I still don't know why it happened but uninstalling my other node packages and reinstalling them all seems to have fixed the issue. Closing issue.

**Comment by brentvatne** [comment]
That's odd! Thanks for the follow up @MossP!

**Comment by MossP** [comment]
np. Thanks for the component, very useful :)
