### ISSUE TITLE
Full screen with UINavigationBar outside of ReactView

### ISSUE THREAD

**Issue by jessepollak** [brentvatne/react-native-modal#22]
I'm trying to use the modal and have it go full screen. Unfortunately, I have a UINavigationBar outside of the ReactView which is causing problems. It seems as though it is taking the size of the ReactView rather than the main view.

![screenshot 2015-05-21 12 35 13](https://cloud.githubusercontent.com/assets/1097953/7757334/52be93a0-ffb6-11e4-8d78-4c84f1116590.png)

Any ideas on how to approach this issue?

**Comment by brentvatne** [comment]
@jessepollak - does this happen with `forceToFront` enabled?

**Comment by jessepollak** [comment]
Yep, when `forceToFront` isn't enabled, it looks like this.

![screenshot 2015-05-21 13 07 12](https://cloud.githubusercontent.com/assets/1097953/7757876/59b04704-ffba-11e4-8d95-d16e77511f76.png)

**Comment by Iliker** [comment]
+1 when forceToFront={true}, it looks like this.
![2015-05-22 2 37 30](https://cloud.githubusercontent.com/assets/7972127/7765399/1d2092f4-0090-11e5-8f67-8cdc3f673d18.png)

**Comment by brentvatne** [comment]
Thanks for the reports guys! I'll try to take care of these this weekend

**Comment by grabbou** [comment]
Same here. Just saying.

**Comment by grabbou** [comment]
It's probably because of the React calculating absolute positions relative to the parent view, not to the UIWindow the element has been attached to. Not sure if coming straightly from React (that would've been super weird) or from `Overlay`, probably needs some investigating, but below is my tip that made it working.

Copy the `Styles.js` from this repo, define them in your project and change the `container` part to this one:

``` js
import Dimensions from 'Dimensions';

export default StyleSheet.create({
  width: window.width,
  height: window.height,
  position: 'absolute',
  left: 0,
  top: 0
});
```

@brentvatne if this is something you are happy with, I can submit a PR.

**Comment by brentvatne** [comment]
@grabbou - I like it - let's do it :smile:

**Comment by grabbou** [comment]
@brentvatne to the `native-modal` repo? (this one)

**Comment by brentvatne** [comment]
@grabbou - fair question, probably both actually (Overlay and here)

**Comment by grabbou** [comment]
I'll check out Overlay stuff and see if this is something that we can fix there and will work out of the box or not.

**Comment by ghost** [comment]
@grabbou I tried your fix on react-native-overlay. It seems to does the trick :) thanks
