### ISSUE TITLE
Don't open modal if scene is not active [full screen mode]

### ISSUE THREAD

**Issue by grabbou** [brentvatne/react-native-modal#26]
If, by any chance (in my case it was a mistake), two the same Views are in the routes stack and one of them is inactive, when the modal is activated, it appears as many times as number of scenes that contain it in the stack. Not something I'd expected to happen imo. All works well tough, the only drawback is the semi-transparent background gets darker and darker with the number of modals activated.

**Comment by brentvatne** [comment]
Definitely a bug, I might not have a chance to fix this for a few days but feel free to have a crack at it if you need a fix before then

**Comment by akabab** [comment]
looks like I have the same issue, if I have an opened modal and I refresh the simulator (either manually or from live reload) everything gets redrawn exept the modal, so it get stacked over and over.. it's not easy for developping and I don't know where that comes from, it's really weird. Any fix yet ?
