### ISSUE TITLE
Backdrop overlay features

### ISSUE THREAD

**Issue by voronianski** [brentvatne/react-native-modal#3]
- [x] should be optional
- [ ] possibility to have separate animation
- [x] onPress handler as property

**Comment by brentvatne** [comment]
:+1: very much in agreement about all of these options

**Comment by brentvatne** [comment]
@voronianski - took care of 2 of the 3 above in 192248a50b628a12b7f705685bcdde16ffc4b0f0

**Comment by brentvatne** [comment]
I think to make the separate animations work well for this we should move it into a `<ModalBackdrop />` component that also has the `Transitions` mixin included, and can then accept showing and hiding animation functions in the same way as the overall modal.

**Comment by voronianski** [comment]
@brentvatne agree, do you start with it already?

**Comment by brentvatne** [comment]
@voronianski - I didn't yet, feel free to have a go at it, otherwise I'll probably do it this evening :)

**Comment by brentvatne** [comment]
No demand for separate backdrop animation yet so I'll just wait until I need it or someone else does.
