### ISSUE TITLE
Is it necessary to use XCode in this project?

### ISSUE THREAD

**Issue by ghost** [brentvatne/react-native-modal#30]
Like the following:

Add it to your project

Run npm install react-native-modal --save
Open your project in XCode, right click on Libraries and click Add Files to "Your Project Name" (Screenshot) then choose the RNModal.xcodeproj (Screenshot) .
Add libRNModal.a to Build Phases -> Link Binary With Libraries (Screenshot).
var Modal = require('react-native-modal');
At the bottom of your app, add the <Modal> element and use its isVisible prop to toggle visibility. It needs to be at the bottom so that it appears above all other components when it is visible. If you use the forceToFront prop, then the position in the component tree does not matter at all - put it wherever you like.

Thanks!

**Comment by brentvatne** [comment]
It is only necessary if you use `forceToFront` or a blurred background :)
