### ISSUE TITLE
Modal position will not automatically pushed up when in keyboard input mode 

### ISSUE THREAD

**Issue by bright-sea** [brentvatne/react-native-modal#35]
For example, we have some input field in Modal, when we focus on this field, a keyboard will popup and overlay the Modal. We can't see input field and this is bad. 

Is it possible for Modal automatically scroll up to show the input field currently focused?

![screen shot 2015-07-17 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/2636836/8751792/64400de0-2c7d-11e5-82ab-d1f97b4c8b54.png)
![screen shot 2015-07-17 at 12 13 46 pm](https://cloud.githubusercontent.com/assets/2636836/8751791/643f05d0-2c7d-11e5-9af2-ba3372057797.png)

**Comment by grabbou** [comment]
https://medium.com/man-moon/writing-modern-react-native-ui-e317ff956f02 I am using this approach and it works well :)

**Comment by grabbou** [comment]
- this is nice addition:

```
handleModalClick() {
    if (this.props.isKeyboardOpened) {
      return this.refs.form.blur();
    }
    this.props.onClose(false);
  }
```

and pass it to `onPressBackdrop`. Clicking on the background will hide keyboard first instead of the whole modal.
