### ISSUE TITLE
Don't display 'Close' button

### ISSUE THREAD

**Issue by booxood** [brentvatne/react-native-modal#36]
If don't set 'customCloseButton', will don't display 'Close' button.

**Comment by booxood** [comment]
'DefaultStyles' is bad... :joy:

**Comment by brentvatne** [comment]
Oh well that's certainly a bug! Yeah default styles aren't great. I haven't had a chance to work on this for a while but there are definitely some big improvements that can be made here, do you have any time to submit a PR for these issues? I'll take some time soon to convert this to `Animated` and clean it up a bit

**Comment by booxood** [comment]
ok, I will try.

**Comment by booxood** [comment]
Done. And find other new bug ...
