### ISSUE TITLE
Component doesn't work after react-native upgrade to 0.8.0

### ISSUE THREAD

**Issue by aksonov** [brentvatne/react-native-modal#39]
backdrop doesn't work now, content is not shown...

**Comment by manuelkiessling** [comment]
Another error I'm encountering in my react-native 0.8.0 app is that the `closeButton` style doesn't seem to work as intended. The close button is rendered behind the modal content box, instead of the upper right corner of the UI. I'm currently investigating.

**Comment by booxood** [comment]
@manuelkiessling  Maybe you can see #36 about some `closeButton`.
