### ISSUE TITLE
Component doesn't work after react-native upgrade to 0.10.0

### ISSUE THREAD

**Issue by qingfeng** [brentvatne/react-native-modal#42]
![image](https://cloud.githubusercontent.com/assets/18495/9526834/2e0c6b9e-4d1e-11e5-80c1-fb9ae00b3080.png)

**Comment by grabbou** [comment]
@brentvatne any chances you update dependency to 0.3?
https://github.com/brentvatne/react-native-modal/pull/43

**Comment by grabbou** [comment]
Another thing, does not seem to open no matter what's the value of `isOpened`. I am currently investigating that issue, but seems that for some reason `componentWillReceiveProps` is not getting called.

**Comment by cienijr** [comment]
@grabbou please publish the new version to NPM, it still points 0.3.8 as the latest release 😕

**Comment by grabbou** [comment]
Ha, I'd love to, but I don't have any write access yet @brentvatne

**Comment by alfonsodev** [comment]
this issue should be closed as the version in npm is 0.4.0
