### ISSUE TITLE
I am using React Native of 0.10 version. I have copied same sample but still it is not working.

### ISSUE THREAD

**Issue by kamalkrishna3000** [brentvatne/react-native-modal#45]

**Comment by kamalkrishna3000** [comment]
Code I have used 

class  Login extends React.Component {

constructor(props) {
  super(props);
  this.state = {
    searchString: 'admin',
    password : 'admin',
    isModalOpen: true
  };
}
   openModal() {
    this.setState({isModalOpen: true});
  }

  closeModal() {
    this.setState({isModalOpen: false});
  }

  render() {
   return(
    <View style={styles.container}>
    <View style={styles.flowRight}>
  <Text onPress={() => this.openModal()}>
          Open Modal
        </Text>
  <Modal ref={'modal'} duration={1000} visible={this.state.isModalOpen} onClose={() => this.closeModal()}>
          <Text style={styles.text}> Hello world</Text>
        </Modal>

</View>
    </View>
   );
  }
}

**Comment by mhollweck** [comment]
I had the same issue. It seems like the example provided is not up-to-date. I had to change 'isVisible' to 'visible' and it worked.
