### ISSUE TITLE
Add Android support

### ISSUE THREAD

**Issue by aylarov** [brentvatne/react-native-modal#46]
It would be great to have this component available for Android

**Comment by ryanmcdermott** [comment]
+1

**Comment by timzaak** [comment]
+1, is there any plan to support Android?

**Comment by saurshaz** [comment]
+1

**Comment by brentvatne** [comment]
I don't have any plans for this @timzaak, but a pull request to add this would be welcome. It shouldn't be too difficult because Android provides `Portal`: https://github.com/facebook/react-native/blob/master/Libraries/Portal/Portal.js - which you can use in place of react-native-overlay

**Comment by dangnelson** [comment]
+1

**Comment by brentvatne** [comment]
PR welcome folks! I don't have any time to work on this right now :(

**Comment by niftylettuce** [comment]
I tried to integrate `Portal` but I couldn't require it - not sure why.

**Comment by prabakarviji** [comment]
Is it possible with RN 0.19? @brentvatne

**Comment by tuneZola** [comment]
+1, @brentvatne, what do you need a PR for? To get the Portal out? I could use it for when its ready? It appears to be in .18, not sure if its in working condition since its not in the docs?
