### ISSUE TITLE
Added this to ReactNativeModules.com

### ISSUE THREAD

**Issue by wootwoot1234** [brentvatne/react-native-modal#5]
I put together http://reactnativemodules.com last night and added your module.  It's a community run list of react native modules.  Hopefully it will make finding projects like these easier.  Am I missing any that you know of?

**Comment by voronianski** [comment]
@wootwoot1234 nice :+1:

**Comment by brentvatne** [comment]
thanks @wootwoot1234! it looks like you have a pretty good list going
