### ISSUE TITLE
The transparent background doesn't fade in but slide in

### ISSUE THREAD

**Issue by koppelaar** [brentvatne/react-native-modal#52]
If you look at native apps, the transparent background of a modal never slides in, like with this component, but it fades in. The modal itself does slide in. 

With this component a black background slides in from the bottom, which feels very broken from a UI point of view.

**Comment by brentvatne** [comment]
That's a fair point! I don't use this library anymore but if you would like to fix it that would be welcome! It shouldn't be very hard

**Comment by mschipperheyn** [comment]
Just curious. Do you use another library?

**Comment by brentvatne** [comment]
@mschipperheyn - I just put a component at the top-level of the app and do position absolute top 0 left 0 bottom 0 right 0 :)
