### ISSUE TITLE
Failed to import module

### ISSUE THREAD

**Issue by ssmlee04** [brentvatne/react-native-modal#56]
I was trying to do 

`import Modal from 'react-native-modal'` or simply `var Modal = require('react-native-modal')`

and I got the following error messages

![](http://i.stack.imgur.com/ZJkcF.jpg)

Wondering what might be the problem? My RN is 0.31.0. RN-modal version is 0.4.0

**Comment by franrios** [comment]
Same issue here

**Comment by brentvatne** [comment]
hi there! this library is no longer under active development, if you wish to take it over, let me know here
